mutation addRoom($name: String!, $intro: String!, $invite_code: String!) {
  insert_room_one(object: {name: $name, intro: $intro, invite_code: $invite_code}) {
    uuid
  }
}

query getJoinedRooms($user_uuid: uuid!) {
  user_room(where: {user_uuid: {_eq: $user_uuid}}) {
    room {
      uuid
      name
      intro
      invite_code
      created_at
    }
  }
}

query getRoomByInviteCode($invite_code: String!) {
  room(where: {invite_code: {_eq: $invite_code}}) {
    uuid
  }
}

mutation joinRoom($user_uuid: uuid!, $room_uuid: uuid!) {
  insert_user_room_one(object: {user_uuid: $user_uuid, room_uuid: $room_uuid}) {
    user_uuid
    room_uuid
  }
}

mutation updateRoomIntro($uuid: uuid!, $intro: String!) {
  update_room_by_pk(pk_columns: {uuid: $uuid}, _set: {intro: $intro}) {
    uuid
    intro
  }
}

mutation leaveRoom($user_uuid: uuid!, $room_uuid: uuid!) {
  delete_user_room_by_pk(user_uuid: $user_uuid, room_uuid: $room_uuid) {
    user_uuid
  }
}

query getRoomMembers($room_uuid: uuid!) {
  user_room(where: {room_uuid: {_eq: $room_uuid}}) {
    user {
      uuid
      username
    }
  }
}
